CC := $(ATH_CROSS_COMPILE_TYPE)gcc

all:
	$(CC) -DAR6001 -Wall -I../../include -I../../os/linux/include -I../../../include -I../../../include/AR6001 eeprom.c -o eeprom.AR6001

	$(CC) -DAR6002 -Wall -I../../include -I../../os/linux/include -I../../../include -I../../../include/AR6002/hw2.0 eeprom.c -o eeprom.AR6002
    